spring:
    datasource:
        url: jdbc:mysql://localhost:3306/my_items_am?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root

    mail:
        host: smtp.gmail.com
        username: 2021JavaForTest@gmail.com
        password: forTest2021
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

myitems:
    upload:
        path: /Users/karen/data/lessons/Java2021New/maven/springMyItems/images/